openapi: 3.0.0
info:
  title: Linux Broker Scheduled Task API
  version: 1.0.0
  description: |
    API for managing Linux virtual machines, enabling the return of VMs, updating network connectivity status, and initiating scaling operations to power on or off machines based on system analysis.
servers:
  - url: /api
paths:
  /vms:
    get:
      operationId: GetVms
      summary: Retrieve a list of all virtual machines
      responses:
        "200":
          description: A list of VMs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "404":
          description: No VMs found or database issue
        "500":
          description: Unexpected error occurred

  /vms/{vmid}/update-attributes:
    post:
      operationId: UpdateVmAttributes
      summary: Update attributes of a specific virtual machine
      parameters:
        - name: vmid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: The VM attribute update details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                powerstate:
                  type: string
                networkstatus:
                  type: string
                vmstatus:
                  type: string
      responses:
        "200":
          description: Successfully updated VM attributes
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Invalid input
        "404":
          description: VM not found or no attributes updated
        "500":
          description: Unexpected error occurred

  /vms/released:
    post:
      operationId: ReturnReleasedVms
      summary: Return all released virtual machines
      responses:
        "200":
          description: Successfully returned released VMs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    VMID:
                      type: integer
                      description: The ID of the virtual machine
                    Hostname:
                      type: string
                      description: The hostname of the virtual machine
                    IPAddress:
                      type: string
                      description: The IP address of the virtual machine
                    PowerState:
                      type: string
                      description: The power state of the virtual machine
                    NetworkStatus:
                      type: string
                      description: The network status of the virtual machine
                    VmStatus:
                      type: string
                      description: The status of the virtual machine
                    LastUpdateDate:
                      type: string
                      format: date-time
                      description: The last update date of the virtual machine
        "500":
          description: Unexpected error occurred
  
  /scaling/trigger:
    post:
      operationId: TriggerScalingLogic
      summary: Trigger the scaling logic for virtual machines
      description: |
        This endpoint triggers the scaling logic for virtual machines based on predefined scaling rules.
      responses:
        "200":
          description: Successfully triggered the scaling logic
          content:
            application/json:
              schema:
                type: object
                properties:
                  PoweredOnVMs:
                    type: array
                    description: List of VMs that were powered on
                    items:
                      type: string
                  PoweredOffVMs:
                    type: array
                    description: List of VMs that were powered off
                    items:
                      type: string
        "500":
          description: Internal server error or failure to trigger scaling logic
