openapi: 3.0.0
info:
  title: Linux Broker Avd Host API
  version: 1.0.0
  description: API for managing the checkout of linux virtual machines.
servers:
  - url: /api
paths:
  /vms/checkout:
    post:
      operationId: CheckoutVm
      summary: Checkout a virtual machine
      requestBody:
        description: The VM checkout details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                avdhost:
                  type: string
      responses:
        "200":
          description: Successfully checked out VM
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Invalid input
        "409":
          description: No available VM found
        "500":
          description: Unexpected error occurred
